# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kimbring2/Twini-Golf

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kimbring2/Twini-Golf

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kimbring2/Twini-Golf/CMakeFiles /home/kimbring2/Twini-Golf//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kimbring2/Twini-Golf/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named libvizgolf_static

# Build rule for target.
libvizgolf_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libvizgolf_static
.PHONY : libvizgolf_static

# fast build rule for target.
libvizgolf_static/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvizgolf_static.dir/build.make CMakeFiles/libvizgolf_static.dir/build
.PHONY : libvizgolf_static/fast

#=============================================================================
# Target rules for targets named golf_game

# Build rule for target.
golf_game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 golf_game
.PHONY : golf_game

# fast build rule for target.
golf_game/fast:
	$(MAKE) $(MAKESILENT) -f src/lib_python/CMakeFiles/golf_game.dir/build.make src/lib_python/CMakeFiles/golf_game.dir/build
.PHONY : golf_game/fast

#=============================================================================
# Target rules for targets named golf_controller

# Build rule for target.
golf_controller: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 golf_controller
.PHONY : golf_controller

# fast build rule for target.
golf_controller/fast:
	$(MAKE) $(MAKESILENT) -f src/lib_python/CMakeFiles/golf_controller.dir/build.make src/lib_python/CMakeFiles/golf_controller.dir/build
.PHONY : golf_controller/fast

#=============================================================================
# Target rules for targets named golf_shared_memory

# Build rule for target.
golf_shared_memory: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 golf_shared_memory
.PHONY : golf_shared_memory

# fast build rule for target.
golf_shared_memory/fast:
	$(MAKE) $(MAKESILENT) -f src/lib_python/CMakeFiles/golf_shared_memory.dir/build.make src/lib_python/CMakeFiles/golf_shared_memory.dir/build
.PHONY : golf_shared_memory/fast

#=============================================================================
# Target rules for targets named golf_exception

# Build rule for target.
golf_exception: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 golf_exception
.PHONY : golf_exception

# fast build rule for target.
golf_exception/fast:
	$(MAKE) $(MAKESILENT) -f src/lib_python/CMakeFiles/golf_exception.dir/build.make src/lib_python/CMakeFiles/golf_exception.dir/build
.PHONY : golf_exception/fast

#=============================================================================
# Target rules for targets named vizgolf

# Build rule for target.
vizgolf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vizgolf
.PHONY : vizgolf

# fast build rule for target.
vizgolf/fast:
	$(MAKE) $(MAKESILENT) -f src/lib_python/CMakeFiles/vizgolf.dir/build.make src/lib_python/CMakeFiles/vizgolf.dir/build
.PHONY : vizgolf/fast

#=============================================================================
# Target rules for targets named twingolf

# Build rule for target.
twingolf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 twingolf
.PHONY : twingolf

# fast build rule for target.
twingolf/fast:
	$(MAKE) $(MAKESILENT) -f src/vizgolf/CMakeFiles/twingolf.dir/build.make src/vizgolf/CMakeFiles/twingolf.dir/build
.PHONY : twingolf/fast

src/lib/ViZGolfController.o: src/lib/ViZGolfController.cpp.o
.PHONY : src/lib/ViZGolfController.o

# target to build an object file
src/lib/ViZGolfController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvizgolf_static.dir/build.make CMakeFiles/libvizgolf_static.dir/src/lib/ViZGolfController.cpp.o
.PHONY : src/lib/ViZGolfController.cpp.o

src/lib/ViZGolfController.i: src/lib/ViZGolfController.cpp.i
.PHONY : src/lib/ViZGolfController.i

# target to preprocess a source file
src/lib/ViZGolfController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvizgolf_static.dir/build.make CMakeFiles/libvizgolf_static.dir/src/lib/ViZGolfController.cpp.i
.PHONY : src/lib/ViZGolfController.cpp.i

src/lib/ViZGolfController.s: src/lib/ViZGolfController.cpp.s
.PHONY : src/lib/ViZGolfController.s

# target to generate assembly for a file
src/lib/ViZGolfController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvizgolf_static.dir/build.make CMakeFiles/libvizgolf_static.dir/src/lib/ViZGolfController.cpp.s
.PHONY : src/lib/ViZGolfController.cpp.s

src/lib/ViZGolfExceptions.o: src/lib/ViZGolfExceptions.cpp.o
.PHONY : src/lib/ViZGolfExceptions.o

# target to build an object file
src/lib/ViZGolfExceptions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvizgolf_static.dir/build.make CMakeFiles/libvizgolf_static.dir/src/lib/ViZGolfExceptions.cpp.o
.PHONY : src/lib/ViZGolfExceptions.cpp.o

src/lib/ViZGolfExceptions.i: src/lib/ViZGolfExceptions.cpp.i
.PHONY : src/lib/ViZGolfExceptions.i

# target to preprocess a source file
src/lib/ViZGolfExceptions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvizgolf_static.dir/build.make CMakeFiles/libvizgolf_static.dir/src/lib/ViZGolfExceptions.cpp.i
.PHONY : src/lib/ViZGolfExceptions.cpp.i

src/lib/ViZGolfExceptions.s: src/lib/ViZGolfExceptions.cpp.s
.PHONY : src/lib/ViZGolfExceptions.s

# target to generate assembly for a file
src/lib/ViZGolfExceptions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvizgolf_static.dir/build.make CMakeFiles/libvizgolf_static.dir/src/lib/ViZGolfExceptions.cpp.s
.PHONY : src/lib/ViZGolfExceptions.cpp.s

src/lib/ViZGolfGame.o: src/lib/ViZGolfGame.cpp.o
.PHONY : src/lib/ViZGolfGame.o

# target to build an object file
src/lib/ViZGolfGame.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvizgolf_static.dir/build.make CMakeFiles/libvizgolf_static.dir/src/lib/ViZGolfGame.cpp.o
.PHONY : src/lib/ViZGolfGame.cpp.o

src/lib/ViZGolfGame.i: src/lib/ViZGolfGame.cpp.i
.PHONY : src/lib/ViZGolfGame.i

# target to preprocess a source file
src/lib/ViZGolfGame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvizgolf_static.dir/build.make CMakeFiles/libvizgolf_static.dir/src/lib/ViZGolfGame.cpp.i
.PHONY : src/lib/ViZGolfGame.cpp.i

src/lib/ViZGolfGame.s: src/lib/ViZGolfGame.cpp.s
.PHONY : src/lib/ViZGolfGame.s

# target to generate assembly for a file
src/lib/ViZGolfGame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvizgolf_static.dir/build.make CMakeFiles/libvizgolf_static.dir/src/lib/ViZGolfGame.cpp.s
.PHONY : src/lib/ViZGolfGame.cpp.s

src/lib/ViZGolfMessageQueue.o: src/lib/ViZGolfMessageQueue.cpp.o
.PHONY : src/lib/ViZGolfMessageQueue.o

# target to build an object file
src/lib/ViZGolfMessageQueue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvizgolf_static.dir/build.make CMakeFiles/libvizgolf_static.dir/src/lib/ViZGolfMessageQueue.cpp.o
.PHONY : src/lib/ViZGolfMessageQueue.cpp.o

src/lib/ViZGolfMessageQueue.i: src/lib/ViZGolfMessageQueue.cpp.i
.PHONY : src/lib/ViZGolfMessageQueue.i

# target to preprocess a source file
src/lib/ViZGolfMessageQueue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvizgolf_static.dir/build.make CMakeFiles/libvizgolf_static.dir/src/lib/ViZGolfMessageQueue.cpp.i
.PHONY : src/lib/ViZGolfMessageQueue.cpp.i

src/lib/ViZGolfMessageQueue.s: src/lib/ViZGolfMessageQueue.cpp.s
.PHONY : src/lib/ViZGolfMessageQueue.s

# target to generate assembly for a file
src/lib/ViZGolfMessageQueue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvizgolf_static.dir/build.make CMakeFiles/libvizgolf_static.dir/src/lib/ViZGolfMessageQueue.cpp.s
.PHONY : src/lib/ViZGolfMessageQueue.cpp.s

src/lib/ViZGolfSharedMemory.o: src/lib/ViZGolfSharedMemory.cpp.o
.PHONY : src/lib/ViZGolfSharedMemory.o

# target to build an object file
src/lib/ViZGolfSharedMemory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvizgolf_static.dir/build.make CMakeFiles/libvizgolf_static.dir/src/lib/ViZGolfSharedMemory.cpp.o
.PHONY : src/lib/ViZGolfSharedMemory.cpp.o

src/lib/ViZGolfSharedMemory.i: src/lib/ViZGolfSharedMemory.cpp.i
.PHONY : src/lib/ViZGolfSharedMemory.i

# target to preprocess a source file
src/lib/ViZGolfSharedMemory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvizgolf_static.dir/build.make CMakeFiles/libvizgolf_static.dir/src/lib/ViZGolfSharedMemory.cpp.i
.PHONY : src/lib/ViZGolfSharedMemory.cpp.i

src/lib/ViZGolfSharedMemory.s: src/lib/ViZGolfSharedMemory.cpp.s
.PHONY : src/lib/ViZGolfSharedMemory.s

# target to generate assembly for a file
src/lib/ViZGolfSharedMemory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/libvizgolf_static.dir/build.make CMakeFiles/libvizgolf_static.dir/src/lib/ViZGolfSharedMemory.cpp.s
.PHONY : src/lib/ViZGolfSharedMemory.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... golf_controller"
	@echo "... golf_exception"
	@echo "... golf_game"
	@echo "... golf_shared_memory"
	@echo "... libvizgolf_static"
	@echo "... twingolf"
	@echo "... vizgolf"
	@echo "... src/lib/ViZGolfController.o"
	@echo "... src/lib/ViZGolfController.i"
	@echo "... src/lib/ViZGolfController.s"
	@echo "... src/lib/ViZGolfExceptions.o"
	@echo "... src/lib/ViZGolfExceptions.i"
	@echo "... src/lib/ViZGolfExceptions.s"
	@echo "... src/lib/ViZGolfGame.o"
	@echo "... src/lib/ViZGolfGame.i"
	@echo "... src/lib/ViZGolfGame.s"
	@echo "... src/lib/ViZGolfMessageQueue.o"
	@echo "... src/lib/ViZGolfMessageQueue.i"
	@echo "... src/lib/ViZGolfMessageQueue.s"
	@echo "... src/lib/ViZGolfSharedMemory.o"
	@echo "... src/lib/ViZGolfSharedMemory.i"
	@echo "... src/lib/ViZGolfSharedMemory.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

